# -*- coding: utf-8 -*-
"""TL_basesupermercado_G16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qbrsthXiDJxyqNKBUaaW3u-rwM326PRj

#Data Exporatory Analysis and Modeling

Tomando como base la forma normal de "base supermercado" generada, analizaremos cada tabla, generaremos y modelaremos un OLAP para su posterior analisis en Power BI.

##Importamos librerías y la Base de Datos de Supermercado
"""

from google.colab import files
from google.colab import drive

drive.mount('/content/drive')

"""Librerías que vamos a utilizar"""

import pandas as pd

"""##Maestro Ordenes y Métodos de Pago"""

#Cargamos tabla de ordenes
ot_ordenes_detalle = pd.read_csv(r'C:\Users\fedel\OneDrive\Escritorio\Documents\csv-20241003T214749Z-001\csv\bs_ordenes_det_mod_1.csv')
ot_ordenes_detalle.head()
#Agregamos etiqueta de operación
ot_ordenes_detalle['operacion'] = 'venta'
#Creamos el indice que va a ser el PK de la tabla final
ot_ordenes_detalle['id_ord_total'] = ot_ordenes_detalle['id_ord_prod'] + "_" + "v"
ot_ordenes_detalle.head()
ot_ordenes_detalle.columns
ot_ordenes_detalle = ot_ordenes_detalle.reindex(['id_ord_total', 'operacion', 'id_ord_prod', 'idOrden', 'idProducto', 'cantidad', 'precioUnitario','precio'],axis=1)
ot_ordenes_detalle.head()

#Cargamos las devoluciones
bs_devoluciones_1 = pd.read_csv(r'C:\Users\fedel\OneDrive\Escritorio\Documents\csv-20241003T214749Z-001\csv\bs_devoluciones_1.csv')
bs_devoluciones_2 = pd.read_csv(r'C:\Users\fedel\OneDrive\Escritorio\Documents\csv-20241003T214749Z-001\csv\bs_devoluciones_2.csv')
bs_devoluciones_3 = pd.read_csv(r'C:\Users\fedel\OneDrive\Escritorio\Documents\csv-20241003T214749Z-001\csv\bs_devoluciones_3.csv')
bs_devoluciones_4 = pd.read_csv(r'C:\Users\fedel\OneDrive\Escritorio\Documents\csv-20241003T214749Z-001\csv\bs_devoluciones_4.csv')
bs_devoluciones_5 = pd.read_csv(r'C:\Users\fedel\OneDrive\Escritorio\Documents\csv-20241003T214749Z-001\csv\bs_devoluciones_5.csv')

bs_devoluciones_3.columns
#Combinamos las tablas, desnomarlizamos
bs_devoluciones_2 = pd.merge(bs_devoluciones_2, bs_devoluciones_3[['id_motdev', 'motivoDevolucion']], left_on='id_motdev', right_on='id_motdev', how='left')
bs_devoluciones_2 = bs_devoluciones_2.drop('id_motdev', axis=1)
bs_devoluciones_2

#Dejamos la tabla devoluciones desnormalizada para combinar
bs_devoluciones_4 = pd.merge(bs_devoluciones_4, bs_devoluciones_5[['id_resol', 'resolucion']], left_on='id_resol', right_on='id_resol', how='left')
bs_devoluciones_4 = bs_devoluciones_4.drop('id_resol', axis=1)
bs_devoluciones_4

#Combinamos con la principal
bs_devoluciones_1 = pd.merge(bs_devoluciones_1, bs_devoluciones_2[['id_ord_prod', 'motivoDevolucion']], left_on='id_ord_prod', right_on='id_ord_prod', how='left')
bs_devoluciones_1 = pd.merge(bs_devoluciones_1, bs_devoluciones_4[['id_ord_prod', 'resolucion']], left_on='id_ord_prod', right_on='id_ord_prod', how='left')
bs_devoluciones_1
bs_devoluciones_1.columns
bs_devoluciones_1['operacion'] = 'devolucion'
bs_devoluciones_1['id_ord_total'] = bs_devoluciones_1['id_ord_prod'] + "_" + "d"
bs_devoluciones_1.columns

bs_devoluciones_1 = bs_devoluciones_1.reindex(['id_ord_total', 'operacion', 'id_ord_prod', 'idOrden', 'idProducto', 'cantidadDevuelta', 'fechaDevolucion', 'motivoDevolucion', 'resolucion'],axis=1)
bs_devoluciones_1.head()

#Contatenamos ambas tablas para crear Ordenes_total
bs_ordenes_total = pd.concat([ot_ordenes_detalle, bs_devoluciones_1], ignore_index=True)
bs_ordenes_total.head()

#Cargamos tabla de ordenes que tiene información de medios de pagos, y clientes.
bs_ordenes_1 = pd.read_csv(r'C:\Users\fedel\OneDrive\Escritorio\Documents\csv-20241003T214749Z-001\csv\bs_ordenes_1.csv')
bs_ordenes_2 = pd.read_csv(r'C:\Users\fedel\OneDrive\Escritorio\Documents\csv-20241003T214749Z-001\csv\bs_ordenes_2.csv')
bs_ordenes_3 = pd.read_csv(r'C:\Users\fedel\OneDrive\Escritorio\Documents\csv-20241003T214749Z-001\csv\bs_ordenes_3.csv')
bs_ordenes_4 = pd.read_csv(r'C:\Users\fedel\OneDrive\Escritorio\Documents\csv-20241003T214749Z-001\csv\bs_ordenes_4.csv')
bs_ordenes_5 = pd.read_csv(r'C:\Users\fedel\OneDrive\Escritorio\Documents\csv-20241003T214749Z-001\csv\bs_ordenes_5.csv')


bs_ordenes_4.columns
bs_ordenes_2.columns
#Combinamos las tablas, desnomarlizamos
bs_ordenes_2 = pd.merge(bs_ordenes_2, bs_ordenes_3[['id_metpago', 'metodoDePago']], left_on='id_metpago', right_on='id_metpago', how='left')
bs_ordenes_2

#Dejamos la tabla devoluciones desnormalizada para combinar
bs_ordenes_4 = pd.merge(bs_ordenes_4, bs_ordenes_5[['id_estado', 'estado']], left_on='id_estado', right_on='id_estado', how='left')
bs_ordenes_4 = bs_ordenes_4.drop('id_estado', axis=1)
bs_ordenes_4

#Combinamos con la principal
bs_ordenes_1 = pd.merge(bs_ordenes_1, bs_ordenes_2[['idOrden', 'id_metpago']], left_on='idOrden', right_on='idOrden', how='left')
bs_ordenes_1 = pd.merge(bs_ordenes_1, bs_ordenes_4[['idOrden', 'estado']], left_on='idOrden', right_on='idOrden', how='left')
bs_ordenes_1
bs_ordenes_1.columns


bs_devoluciones_1 = bs_devoluciones_1.reindex(['id_ord_total', 'operacion', 'id_ord_prod', 'idOrden', 'idProducto', 'cantidadDevuelta', 'fechaDevolucion', 'motivoDevolucion', 'resolucion'],axis=1)
bs_devoluciones_1.head()

bs_ordenes_total = pd.merge(bs_ordenes_total, bs_ordenes_1[['idOrden', 'montoTotal', 'fechaCompra', 'idCliente', 'idSucursal',
       'id_metpago', 'estado']], left_on='idOrden', right_on='idOrden', how='left')

#Exportamos CSV Base ord y base met pago
bs_ordenes_total.to_csv(r'C:\Users\fedel\OneDrive\Escritorio\Documents\csv-20241003T214749Z-001\csv\finales2\bs_ordenes_total.csv', index=False)
bs_ordenes_3.to_csv(r'C:\Users\fedel\OneDrive\Escritorio\Documents\csv-20241003T214749Z-001\csv\finales2\bs_metpago.csv', index=False)

"""##Maestro Clientes"""

bs_maestro_prod_1 = pd.read_csv(r'C:\Users\fedel\OneDrive\Escritorio\Documents\csv-20241003T214749Z-001\csv\bs_maestro_prod_1.csv')
bs_maestro_prod_2 = pd.read_csv(r'C:\Users\fedel\OneDrive\Escritorio\Documents\csv-20241003T214749Z-001\csv\bs_maestro_prod_2.csv')
bs_maestro_prod_3 = pd.read_csv(r'C:\Users\fedel\OneDrive\Escritorio\Documents\csv-20241003T214749Z-001\csv\bs_maestro_prod_3.csv')
bs_maestro_prod_4 = pd.read_csv(r'C:\Users\fedel\OneDrive\Escritorio\Documents\csv-20241003T214749Z-001\csv\bs_maestro_prod_4.csv')
bs_maestro_prod_5 = pd.read_csv(r'C:\Users\fedel\OneDrive\Escritorio\Documents\csv-20241003T214749Z-001\csv\bs_maestro_prod_5.csv')

bs_maestro_prod_2.columns
bs_maestro_prod_3.columns


bs_maestro_prod_2 = pd.merge(bs_maestro_prod_2, bs_maestro_prod_3[['id_uni_medida', 'unidad_medida']], left_on='id_uni_medida', right_on='id_uni_medida', how='left')
bs_maestro_prod_2 = bs_maestro_prod_2.drop('id_uni_medida', axis=1)
bs_maestro_prod_2.head()

bs_maestro_prod_1 = pd.merge(bs_maestro_prod_1, bs_maestro_prod_2[['idProducto', 'precioUnitario', 'cant_medida', 'precio_uni_medida',
       'unidad_medida']], left_on='idProducto', right_on='idProducto', how='left')

bs_maestro_prod_1 = pd.merge(bs_maestro_prod_1, bs_maestro_prod_3[['id_uni_medida', 'unidad_medida']], left_on='id_uni_medida', right_on='id_uni_medida', how='left')

bs_maestro_prod_1.columns

bs_maestro_prod_4 = pd.merge(bs_maestro_prod_4, bs_maestro_prod_5[['idSubcategoria', 'subCategoria', 'categoria']], left_on='idSubcategoria', right_on='idSubcategoria', how='left')
bs_maestro_prod_4 = bs_maestro_prod_4.drop('idSubcategoria', axis=1)
bs_maestro_prod_4.head()
bs_maestro_prod_4.columns

bs_maestro_prod_1 = pd.merge(bs_maestro_prod_1, bs_maestro_prod_4[['idProducto', 'subCategoria', 'categoria']], left_on='idProducto', right_on='idProducto', how='left')
bs_maestro_prod_1
bs_maestro_prod_1.columns

bs_maestro_prod_1.to_csv(r'C:\Users\fedel\OneDrive\Escritorio\Documents\csv-20241003T214749Z-001\csv\finales2\base_maestro_prod.csv', index=False)

"""##Maestro  Sucursales"""

#carga de sucursales
bs_maestro_suc_1 = pd.read_csv(r'C:\Users\fedel\OneDrive\Escritorio\Documents\csv-20241003T214749Z-001\csv\bs_maestro_suc_1 (1).csv')
bs_maestro_suc_2 = pd.read_csv(r'C:\Users\fedel\OneDrive\Escritorio\Documents\csv-20241003T214749Z-001\csv\bs_maestro_suc_2 (1).csv')
bs_maestro_suc_3 = pd.read_csv(r'C:\Users\fedel\OneDrive\Escritorio\Documents\csv-20241003T214749Z-001\csv\bs_maestro_suc_3 (1).csv')
bs_maestro_suc_4 = pd.read_csv(r'C:\Users\fedel\OneDrive\Escritorio\Documents\csv-20241003T214749Z-001\csv\bs_maestro_suc_4_unpivoted (1).csv')
bs_maestro_suc_5 = pd.read_csv(r'C:\Users\fedel\OneDrive\Escritorio\Documents\csv-20241003T214749Z-001\csv\bs_maestro_suc_5 (1).csv')
bs_maestro_suc_6 = pd.read_csv(r'C:\Users\fedel\OneDrive\Escritorio\Documents\csv-20241003T214749Z-001\csv\bs_maestro_suc_6 (1).csv')


bs_maestro_suc_2 = pd.merge(bs_maestro_suc_2, bs_maestro_suc_3[['id_provincia', 'provincia']], left_on='id_provincia', right_on='id_provincia', how='left')
bs_maestro_suc_2 = bs_maestro_suc_2.drop('id_provincia', axis=1)
bs_maestro_suc_2

bs_maestro_suc_4.columns
bs_maestro_suc_4 = pd.merge(bs_maestro_suc_4, bs_maestro_suc_5[['id_dia', 'dia']], left_on='id_dia', right_on='id_dia', how='left')
bs_maestro_suc_4 = bs_maestro_suc_4.drop('id_dia', axis=1)

bs_maestro_suc_6.columns
bs_maestro_suc_4 = pd.merge(bs_maestro_suc_4, bs_maestro_suc_6[['id_horario', 'hs_apertura', 'hs_cierre', 'estado']], left_on='id_horario', right_on='id_horario', how='left')
bs_maestro_suc_4 = bs_maestro_suc_4.drop('id_horario', axis=1)
bs_maestro_suc_4

bs_maestro_suc_1 = pd.merge(bs_maestro_suc_1, bs_maestro_suc_4[['idSucursal', 'dia', 'hs_apertura', 'hs_cierre', 'estado']], left_on='idSucursal', right_on='idSucursal', how='left')
bs_maestro_suc_1 = bs_maestro_suc_1.rename(columns={'estado_x':'estado','estado_y':'estado_dia'})
bs_maestro_suc_1.columns

bs_maestro_suc_1_dina = bs_maestro_suc_1.pivot(index=['idSucursal', 'nombre', 'fechaAlta', 'fechaBaja','estado'],
                    columns='dia',
                    values=['hs_apertura', 'hs_cierre']).reset_index()


bs_maestro_suc_1_dina.columns = [f'{col[1]}_{col[0]}' for col in bs_maestro_suc_1_dina.columns]

bs_maestro_suc_1_dina = bs_maestro_suc_1_dina.rename(columns={'_idSucursal':'idSucursal','_nombre':'nombre','_fechaAlta':'fechaAlta','_fechaBaja':'fechaBaja','_estado':'estado'})
#bs_maestro_suc_1_dt = bs_maestro_suc_1_dt.reset_index(drop=True)


bs_maestro_suc_1_dina.columns
bs_maestro_suc_1_dina.info()

bs_maestro_suc_2
bs_maestro_suc_1_dina = pd.merge(bs_maestro_suc_1_dina, bs_maestro_suc_2[['idSucursal', 'direccion', 'localidad', 'provincia']], left_on='idSucursal', right_on='idSucursal', how='left')

bs_maestro_suc_1_dina = bs_maestro_suc_1_dina.reindex(['idSucursal', 'nombre', 'fechaAlta', 'fechaBaja', 'estado', 'direccion','localidad', 'provincia',
       'Lunes_hs_apertura', 'Lunes_hs_cierre', 'Martes_hs_apertura', 'Martes_hs_cierre',
        'Miercoles_hs_apertura','Miercoles_hs_cierre', 'Jueves_hs_apertura', 'Jueves_hs_cierre',
        'Viernes_hs_apertura','Viernes_hs_cierre','Sabado_hs_apertura','Sabado_hs_cierre',
        'Domingo_hs_apertura','Domingo_hs_cierre'], axis=1)


bs_maestro_suc_1_dina.to_csv(r'C:\Users\fedel\OneDrive\Escritorio\Documents\csv-20241003T214749Z-001\csv\finales2\base_maestro_sucursal.csv', index=False)

"""##Maestro  Clientes"""

#maestro de clientes
bs_maestro_clientes_1 = pd.read_csv(r'C:\Users\fedel\OneDrive\Escritorio\Documents\csv-20241003T214749Z-001\csv\bs_maestro_clientes_1.csv')
bs_maestro_clientes_2 = pd.read_csv(r'C:\Users\fedel\OneDrive\Escritorio\Documents\csv-20241003T214749Z-001\csv\bs_maestro_clientes_2.csv')
bs_maestro_clientes_3 = pd.read_csv(r'C:\Users\fedel\OneDrive\Escritorio\Documents\csv-20241003T214749Z-001\csv\bs_maestro_clientes_3.csv')
bs_maestro_clientes_4 = pd.read_csv(r'C:\Users\fedel\OneDrive\Escritorio\Documents\csv-20241003T214749Z-001\csv\bs_maestro_clientes_4.csv')
bs_maestro_clientes_5 = pd.read_csv(r'C:\Users\fedel\OneDrive\Escritorio\Documents\csv-20241003T214749Z-001\csv\bs_maestro_clientes_5.csv')

bs_maestro_clientes_4 = pd.merge(bs_maestro_clientes_4, bs_maestro_clientes_5[['id_prov', 'provincia']], left_on='id_prov', right_on='id_prov', how='left')
bs_maestro_clientes_4 = bs_maestro_clientes_4.drop('id_prov', axis=1)

bs_maestro_clientes_2 = pd.merge(bs_maestro_clientes_2, bs_maestro_clientes_3[['id_genero', 'genero']], left_on='id_genero', right_on='id_genero', how='left')
bs_maestro_clientes_2 = bs_maestro_clientes_2.drop('id_genero', axis=1)

bs_maestro_clientes_1 = pd.merge(bs_maestro_clientes_1, bs_maestro_clientes_2[['idCliente', 'genero']], left_on='idCliente', right_on='idCliente', how='left')
bs_maestro_clientes_1

bs_maestro_clientes_1 = pd.merge(bs_maestro_clientes_1, bs_maestro_clientes_4[['idCliente', 'provincia']], left_on='idCliente', right_on='idCliente', how='left')
bs_maestro_clientes_1

bs_maestro_clientes_1.to_csv(r'C:\Users\fedel\OneDrive\Escritorio\Documents\csv-20241003T214749Z-001\csv\finales2\base_maestro_clientes.csv', index=False)

"""##Creación Base SQL - en servidor"""

#SQL para base_maestro_clientes.csv:
CREATE TABLE base_maestro_clientes (
  idCliente INT,
  fechaAlta VARCHAR(255),
  fechaNacimiento VARCHAR(255),
  nombre VARCHAR(255),
  apellido VARCHAR(255),
  email VARCHAR(255),
  fechaBaja FLOAT,
  estado FLOAT,
  genero VARCHAR(255),
  provincia VARCHAR(255)
);

#SQL para base_maestro_prod.csv:
CREATE TABLE base_maestro_prod (
  idProducto INT,
  fechaAlta VARCHAR(255),
  descripcion VARCHAR(255),
  fechaBaja FLOAT,
  estado FLOAT,
  tiene_oferta VARCHAR(255),
  precioUnitario FLOAT,
  cant_medida FLOAT,
  precio_uni_medida FLOAT,
  unidad_medida VARCHAR(255),
  subCategoria VARCHAR(255),
  categoria VARCHAR(255)
);

#SQL para base_maestro_sucursal.csv:
CREATE TABLE base_maestro_sucursal (
  idSucursal INT,
  nombre VARCHAR(255),
  fechaAlta VARCHAR(255),
  fechaBaja FLOAT,
  estado FLOAT,
  direccion VARCHAR(255),
  localidad VARCHAR(255),
  provincia VARCHAR(255),
  Lunes_hs_apertura VARCHAR(255),
  Lunes_hs_cierre VARCHAR(255),
  Martes_hs_apertura VARCHAR(255),
  Martes_hs_cierre VARCHAR(255),
  Miercoles_hs_apertura VARCHAR(255),
  Miercoles_hs_cierre VARCHAR(255),
  Jueves_hs_apertura VARCHAR(255),
  Jueves_hs_cierre VARCHAR(255),
  Viernes_hs_apertura VARCHAR(255),
  Viernes_hs_cierre VARCHAR(255),
  Sabado_hs_apertura VARCHAR(255),
  Sabado_hs_cierre VARCHAR(255),
  Domingo_hs_apertura VARCHAR(255),
  Domingo_hs_cierre VARCHAR(255)
);

#SQL para bs_metpago.csv:
CREATE TABLE bs_metpago (
  id_metpago INT,
  metodoDePago VARCHAR(255)
);

#SQL para bs_ordenes_total.csv:
CREATE TABLE bs_ordenes_total (
  id_ord_total VARCHAR(255),
  operacion VARCHAR(255),
  id_ord_prod VARCHAR(255),
  idOrden INT,
  idProducto INT,
  cantidad FLOAT,
  precioUnitario FLOAT,
  precio FLOAT,
  cantidadDevuelta FLOAT,
  fechaDevolucion VARCHAR(255),
  motivoDevolucion VARCHAR(255),
  resolucion VARCHAR(255),
  montoTotal FLOAT,
  fechaCompra VARCHAR(255),
  idCliente INT,
  idSucursal INT,
  id_metpago INT,
  estado VARCHAR(255)
);

"""##Carga SQL"""

# Conexión a la DDBB
from sqlalchemy import create_engine

USERNAME = "root"
PASSWORD = ""
BBDD = "supermercado_OLAP"
PORT = "3306"  # Puerto por defecto para MySQL
SERVICE = "localhost"

# Lista de archivos CSV
csv_files = ["base_maestro_clientes.csv", "base_maestro_prod.csv", "base_maestro_sucursal.csv", "bs_metpago.csv", "bs_ordenes_total.csv"]

if __name__ == "__main__":
    # Creación del motor de conexión
    engine = create_engine(f'mysql+mysqlconnector://{USERNAME}:{PASSWORD}@{SERVICE}:{PORT}/{BBDD}', echo=False)

    # Cargar los CSVs en las tablas
    for csv_file in csv_files:
        table_name = csv_file.split(".")[0]
        df = pd.read_csv(csv_file)
        df.to_sql(table_name, engine, index=False, if_exists='replace')
        print(f"Datos cargados en la tabla {table_name}")